// 100+ runnable Python projects. Every line of `code` is commented so the
// project detail page can render a line-by-line walkthrough automatically.

export type Project = {
  slug: string;
  title: string;
  category: string;
  summary: string;
  stack: string[];
  code: string;
};

const P = (p: Project) => p;

export const projects: Project[] = [
  // ============================================================
  // BASICS (1-10)
  // ============================================================
  P({
    slug: "hello-world",
    title: "Hello, World!",
    category: "Basics",
    summary: "The classic first Python program.",
    stack: ["print"],
    code: [
      "# print() writes text to standard output followed by a newline.",
      "print(\"Hello, World!\")  # the string literal in quotes is the argument",
    ].join("\n"),
  }),
  P({
    slug: "variables-and-types",
    title: "Variables and Types",
    category: "Basics",
    summary: "Assign values, inspect their types.",
    stack: ["type", "print"],
    code: [
      "name = \"Ada\"          # str: text data, immutable",
      "age = 36                # int: arbitrary-precision integer",
      "pi = 3.14159            # float: IEEE-754 double",
      "is_admin = True         # bool: True / False (subclass of int)",
      "print(name, age, pi, is_admin)            # print accepts many args separated by spaces",
      "print(type(name), type(age), type(pi))    # type() returns the class object",
    ].join("\n"),
  }),
  P({
    slug: "arithmetic",
    title: "Arithmetic Operators",
    category: "Basics",
    summary: "All seven numeric operators in one demo.",
    stack: ["operators"],
    code: [
      "a, b = 17, 5            # tuple unpacking assigns both at once",
      "print(a + b)            # addition         -> 22",
      "print(a - b)            # subtraction      -> 12",
      "print(a * b)            # multiplication   -> 85",
      "print(a / b)            # true division    -> 3.4 (always float)",
      "print(a // b)           # floor division   -> 3   (rounds toward -inf)",
      "print(a % b)            # modulo / remainder -> 2",
      "print(a ** b)           # exponentiation   -> 1419857",
    ].join("\n"),
  }),
  P({
    slug: "input-echo",
    title: "Echo User Input",
    category: "Basics",
    summary: "Read a line from stdin and greet the user.",
    stack: ["input"],
    code: [
      "name = input(\"Your name: \")  # input() blocks until the user hits Enter",
      "print(f\"Hello, {name}!\")     # f-string interpolates the variable inline",
    ].join("\n"),
  }),
  P({
    slug: "if-elif-else",
    title: "If / Elif / Else",
    category: "Basics",
    summary: "Branch based on a numeric grade.",
    stack: ["conditionals"],
    code: [
      "score = 82                       # could come from input(); hard-coded for the demo",
      "if score >= 90:                  # first branch tested",
      "    grade = \"A\"               # 4-space indent is mandatory in Python",
      "elif score >= 80:                # only tested if the previous failed",
      "    grade = \"B\"",
      "elif score >= 70:",
      "    grade = \"C\"",
      "else:                            # default branch when nothing matched",
      "    grade = \"F\"",
      "print(grade)                     # -> B",
    ].join("\n"),
  }),
  P({
    slug: "for-loop-range",
    title: "For Loop with range()",
    category: "Basics",
    summary: "Iterate over a numeric sequence.",
    stack: ["for", "range"],
    code: [
      "# range(start, stop, step) creates a lazy sequence of ints",
      "for i in range(1, 6):     # 1, 2, 3, 4, 5  (stop is exclusive)",
      "    print(i, i * i)       # print the number and its square",
    ].join("\n"),
  }),
  P({
    slug: "while-countdown",
    title: "While Countdown",
    category: "Basics",
    summary: "Loop while a condition holds true.",
    stack: ["while"],
    code: [
      "n = 5                         # starting value",
      "while n > 0:                  # repeat as long as n is positive",
      "    print(n)                  # show current value",
      "    n -= 1                    # decrement so the loop eventually stops",
      "print(\"Lift off!\")          # runs once after the loop exits",
    ].join("\n"),
  }),
  P({
    slug: "function-add",
    title: "Define a Function",
    category: "Basics",
    summary: "Reusable code with parameters and a return value.",
    stack: ["def", "return"],
    code: [
      "def add(a: int, b: int) -> int:  # type hints document intent; not enforced at runtime",
      "    \"\"\"Return the sum of two integers.\"\"\"  # docstring shown by help()",
      "    return a + b                 # produce the result and exit the function",
      "",
      "print(add(2, 3))                  # -> 5",
      "print(add(b=10, a=4))             # keyword arguments make calls self-documenting",
    ].join("\n"),
  }),
  P({
    slug: "list-basics",
    title: "List Basics",
    category: "Basics",
    summary: "Append, index, slice, and iterate.",
    stack: ["list"],
    code: [
      "fruits = [\"apple\", \"banana\", \"cherry\"]  # list literal: ordered, mutable",
      "fruits.append(\"date\")        # add to the end in O(1) amortised",
      "print(fruits[0])              # indexing is zero-based -> apple",
      "print(fruits[-1])             # negative indices count from the end -> date",
      "print(fruits[1:3])            # slicing returns a NEW list -> ['banana','cherry']",
      "for f in fruits:              # iteration yields each element in order",
      "    print(f.upper())          # str.upper() returns an upper-cased copy",
    ].join("\n"),
  }),
  P({
    slug: "dict-basics",
    title: "Dictionary Basics",
    category: "Basics",
    summary: "Key/value lookup, insertion, iteration.",
    stack: ["dict"],
    code: [
      "user = {\"name\": \"Ada\", \"age\": 36}   # dict literal with string keys",
      "user[\"email\"] = \"ada@x.io\"           # insertion is just assignment",
      "print(user[\"name\"])                    # KeyError if the key is missing",
      "print(user.get(\"phone\", \"n/a\"))       # .get returns a default instead of raising",
      "for key, value in user.items():          # .items() yields (key, value) tuples",
      "    print(f\"{key} = {value}\")          # pretty-print each pair",
    ].join("\n"),
  }),

  // ============================================================
  // MATH (11-20)
  // ============================================================
  P({
    slug: "factorial",
    title: "Factorial",
    category: "Math",
    summary: "Iterative factorial without recursion.",
    stack: ["loops"],
    code: [
      "def fact(n: int) -> int:           # accept a non-negative integer",
      "    result = 1                      # product accumulator (1 is the identity for *)",
      "    for i in range(2, n + 1):       # multiply 2..n; range stop is exclusive",
      "        result *= i                 # same as: result = result * i",
      "    return result                   # n! = 1*2*...*n; 0! = 1 by the empty loop",
      "",
      "print(fact(0), fact(5), fact(10))   # 1 120 3628800",
    ].join("\n"),
  }),
  P({
    slug: "fibonacci",
    title: "Fibonacci Sequence",
    category: "Math",
    summary: "Generate the first N Fibonacci numbers.",
    stack: ["loops", "tuple-swap"],
    code: [
      "n = 10                       # how many numbers to print",
      "a, b = 0, 1                  # seed values F(0)=0, F(1)=1",
      "for _ in range(n):           # _ is a throwaway loop variable",
      "    print(a, end=\" \")     # end=' ' keeps everything on one line",
      "    a, b = b, a + b          # tuple-swap advances the sequence in one step",
      "print()                      # final newline so the prompt is clean",
    ].join("\n"),
  }),
  P({
    slug: "prime-check",
    title: "Prime Number Check",
    category: "Math",
    summary: "Trial division up to sqrt(n).",
    stack: ["math"],
    code: [
      "from math import isqrt          # isqrt(n) = integer square root, exact and fast",
      "",
      "def is_prime(n: int) -> bool:   # returns True if n is prime",
      "    if n < 2:                    # 0 and 1 are not prime by definition",
      "        return False",
      "    for d in range(2, isqrt(n) + 1):  # any factor pair has one factor <= sqrt(n)",
      "        if n % d == 0:           # found a divisor -> composite",
      "            return False",
      "    return True                  # no divisor found -> prime",
      "",
      "print([n for n in range(20) if is_prime(n)])  # list comp filters primes < 20",
    ].join("\n"),
  }),
  P({
    slug: "primes-sieve",
    title: "Sieve of Eratosthenes",
    category: "Math",
    summary: "All primes below N in O(N log log N).",
    stack: ["algorithms"],
    code: [
      "N = 50                                 # upper bound (exclusive)",
      "sieve = [True] * N                     # start by assuming every index is prime",
      "sieve[0] = sieve[1] = False            # 0 and 1 are not prime",
      "for i in range(2, int(N ** 0.5) + 1):  # only need to sieve up to sqrt(N)",
      "    if sieve[i]:                       # i is prime -> cross out its multiples",
      "        for j in range(i * i, N, i):   # start at i*i (smaller multiples already done)",
      "            sieve[j] = False           # mark composite",
      "primes = [i for i, p in enumerate(sieve) if p]  # collect indices still marked True",
      "print(primes)                          # [2, 3, 5, 7, 11, ...]",
    ].join("\n"),
  }),
  P({
    slug: "gcd-euclid",
    title: "GCD via Euclid's Algorithm",
    category: "Math",
    summary: "Greatest common divisor without recursion.",
    stack: ["math"],
    code: [
      "def gcd(a: int, b: int) -> int:   # works for any non-negative ints",
      "    while b:                       # loop until b becomes 0",
      "        a, b = b, a % b            # replace (a,b) with (b, a mod b)",
      "    return a                       # when b is 0, a is the gcd",
      "",
      "print(gcd(48, 18))                 # -> 6",
    ].join("\n"),
  }),
  P({
    slug: "lcm",
    title: "Least Common Multiple",
    category: "Math",
    summary: "LCM built from GCD.",
    stack: ["math"],
    code: [
      "from math import gcd                  # stdlib gcd avoids re-implementing it",
      "",
      "def lcm(a: int, b: int) -> int:       # lcm(a,b) = |a*b| / gcd(a,b)",
      "    return abs(a * b) // gcd(a, b)    # // gives an int result",
      "",
      "print(lcm(4, 6), lcm(21, 6))          # 12 42",
    ].join("\n"),
  }),
  P({
    slug: "power-fast",
    title: "Fast Exponentiation",
    category: "Math",
    summary: "Compute a**n in O(log n) multiplications.",
    stack: ["algorithms"],
    code: [
      "def power(a: int, n: int) -> int:   # exponentiation by squaring",
      "    result = 1                       # multiplicative identity",
      "    while n > 0:                     # process bits of n from least to most significant",
      "        if n & 1:                    # if current bit is 1, multiply result by current a",
      "            result *= a",
      "        a *= a                       # square the base for the next bit",
      "        n >>= 1                      # shift n right by one bit",
      "    return result",
      "",
      "print(power(2, 10))                  # 1024",
    ].join("\n"),
  }),
  P({
    slug: "decimal-to-binary",
    title: "Decimal to Binary",
    category: "Math",
    summary: "Convert an integer to its binary string.",
    stack: ["bin"],
    code: [
      "n = 42                          # number to convert",
      "print(bin(n))                   # built-in: prefixed with '0b' -> '0b101010'",
      "print(bin(n)[2:])               # strip the '0b' prefix",
      "",
      "# Manual version for learning:",
      "bits = \"\"                     # accumulator (will be reversed)",
      "x = n                            # copy so we don't mutate n",
      "while x:                         # stop when x is 0",
      "    bits = str(x & 1) + bits     # prepend the least-significant bit",
      "    x >>= 1                      # shift right to expose the next bit",
      "print(bits or \"0\")             # 'or 0' handles the n==0 edge case",
    ].join("\n"),
  }),
  P({
    slug: "quadratic",
    title: "Quadratic Equation Solver",
    category: "Math",
    summary: "Real roots of ax^2 + bx + c = 0.",
    stack: ["math"],
    code: [
      "import math                                  # math.sqrt for real roots",
      "",
      "def solve(a: float, b: float, c: float):     # returns 0, 1, or 2 real roots",
      "    d = b * b - 4 * a * c                    # discriminant",
      "    if d < 0:",
      "        return ()                             # no real roots",
      "    if d == 0:",
      "        return (-b / (2 * a),)                # repeated root",
      "    s = math.sqrt(d)                         # two distinct real roots",
      "    return ((-b + s) / (2 * a), (-b - s) / (2 * a))",
      "",
      "print(solve(1, -3, 2))                       # (2.0, 1.0)",
    ].join("\n"),
  }),
  P({
    slug: "pi-leibniz",
    title: "Approximate Pi (Leibniz)",
    category: "Math",
    summary: "Sum the famous alternating series.",
    stack: ["loops"],
    code: [
      "terms = 100_000             # more terms = closer to pi but slower (this series is slow)",
      "total = 0.0                  # running sum",
      "for k in range(terms):       # k = 0, 1, 2, ...",
      "    sign = 1 if k % 2 == 0 else -1   # alternate + and -",
      "    total += sign / (2 * k + 1)      # 1/1 - 1/3 + 1/5 - 1/7 + ...",
      "pi_approx = 4 * total        # the series converges to pi/4",
      "print(pi_approx)             # ~3.1415",
    ].join("\n"),
  }),

  // ============================================================
  // STRINGS (21-30)
  // ============================================================
  P({
    slug: "reverse-string",
    title: "Reverse a String",
    category: "Strings",
    summary: "Three idiomatic ways to reverse text.",
    stack: ["slicing"],
    code: [
      "s = \"hello\"                       # source string (immutable)",
      "print(s[::-1])                      # extended slice with step -1 = reverse copy",
      "print(\"\".join(reversed(s)))      # reversed() returns an iterator; join concatenates it",
      "",
      "chars = list(s)                     # convert to a mutable list of chars",
      "chars.reverse()                     # in-place reverse",
      "print(\"\".join(chars))             # join back into a string",
    ].join("\n"),
  }),
  P({
    slug: "palindrome",
    title: "Palindrome Check",
    category: "Strings",
    summary: "Detect palindromes, ignoring case and spaces.",
    stack: ["strings"],
    code: [
      "def is_palindrome(s: str) -> bool:           # True if s reads the same both ways",
      "    cleaned = \"\".join(c.lower() for c in s if c.isalnum())  # keep letters/digits only",
      "    return cleaned == cleaned[::-1]          # compare against its reverse",
      "",
      "print(is_palindrome(\"A man, a plan, a canal: Panama\"))  # True",
      "print(is_palindrome(\"hello\"))                            # False",
    ].join("\n"),
  }),
  P({
    slug: "word-count",
    title: "Word Frequency",
    category: "Strings",
    summary: "Count how often each word appears.",
    stack: ["Counter"],
    code: [
      "from collections import Counter                          # specialised dict for counting",
      "",
      "text = \"the quick brown fox jumps over the lazy dog the fox\"",
      "words = text.lower().split()                              # lowercase, split on whitespace",
      "counts = Counter(words)                                   # one-shot count of every item",
      "for word, n in counts.most_common(3):                     # top 3 most frequent",
      "    print(f\"{word}: {n}\")",
    ].join("\n"),
  }),
  P({
    slug: "anagram-check",
    title: "Anagram Check",
    category: "Strings",
    summary: "Two strings are anagrams when they share the same letters.",
    stack: ["sorted"],
    code: [
      "def anagram(a: str, b: str) -> bool:        # case-insensitive, ignores spaces",
      "    norm = lambda s: sorted(s.replace(\" \", \"\").lower())  # normalise + sort chars",
      "    return norm(a) == norm(b)                # equal sorted sequences => anagrams",
      "",
      "print(anagram(\"Listen\", \"Silent\"))     # True",
      "print(anagram(\"hello\", \"world\"))        # False",
    ].join("\n"),
  }),
  P({
    slug: "caesar-cipher",
    title: "Caesar Cipher",
    category: "Strings",
    summary: "Classic shift cipher with wrap-around.",
    stack: ["ord", "chr"],
    code: [
      "def caesar(text: str, shift: int) -> str:        # encode by shifting each letter",
      "    out = []                                       # collect characters then join",
      "    for ch in text:                                # iterate one char at a time",
      "        if ch.isalpha():                           # only shift letters",
      "            base = ord('A') if ch.isupper() else ord('a')  # preserve case",
      "            out.append(chr((ord(ch) - base + shift) % 26 + base))  # modular shift",
      "        else:",
      "            out.append(ch)                         # leave punctuation/spaces alone",
      "    return \"\".join(out)",
      "",
      "print(caesar(\"Hello, World!\", 3))               # 'Khoor, Zruog!'",
      "print(caesar(\"Khoor, Zruog!\", -3))              # decoding = negative shift",
    ].join("\n"),
  }),
  P({
    slug: "vowel-counter",
    title: "Vowel Counter",
    category: "Strings",
    summary: "Count vowels using a generator expression.",
    stack: ["sum", "generator"],
    code: [
      "text = input(\"text: \")                              # ask the user for a string",
      "vowels = set(\"aeiouAEIOU\")                          # set membership is O(1)",
      "count = sum(1 for c in text if c in vowels)            # 1 per vowel, summed",
      "print(f\"{count} vowels\")",
    ].join("\n"),
  }),
  P({
    slug: "title-case",
    title: "Smart Title Case",
    category: "Strings",
    summary: "Capitalise words but keep small words lowercase.",
    stack: ["strings"],
    code: [
      "SMALL = {\"a\", \"an\", \"the\", \"of\", \"in\", \"on\", \"and\", \"or\", \"to\"}  # leave lower",
      "",
      "def smart_title(s: str) -> str:                       # title-case the first/last word too",
      "    words = s.lower().split()                          # normalise then split",
      "    out = []",
      "    for i, w in enumerate(words):                      # enumerate gives index + value",
      "        if i in (0, len(words) - 1) or w not in SMALL: # first / last / non-small",
      "            w = w.capitalize()                         # uppercase first char only",
      "        out.append(w)",
      "    return \" \".join(out)",
      "",
      "print(smart_title(\"the lord of the rings\"))         # 'The Lord of the Rings'",
    ].join("\n"),
  }),
  P({
    slug: "string-compress",
    title: "Run-length Encoding",
    category: "Strings",
    summary: "Compact repeated characters into char+count.",
    stack: ["strings"],
    code: [
      "def rle(s: str) -> str:           # simple loss-less compression for runs of chars",
      "    if not s:                      # empty input -> empty output",
      "        return \"\"",
      "    out = []                       # list of (char, count) chunks",
      "    prev, count = s[0], 1          # remember the previous char and how many in a row",
      "    for ch in s[1:]:               # walk the rest of the string",
      "        if ch == prev:             # same char -> extend the run",
      "            count += 1",
      "        else:                      # run ended -> flush it",
      "            out.append(f\"{prev}{count}\")",
      "            prev, count = ch, 1    # start a new run",
      "    out.append(f\"{prev}{count}\")# don't forget the last run",
      "    return \"\".join(out)",
      "",
      "print(rle(\"aaabbcdddd\"))         # 'a3b2c1d4'",
    ].join("\n"),
  }),
  P({
    slug: "longest-word",
    title: "Longest Word",
    category: "Strings",
    summary: "Find the longest word in a sentence.",
    stack: ["max"],
    code: [
      "sentence = \"The quick brown fox jumps over the lazy dog\"",
      "words = sentence.split()                  # split on whitespace",
      "longest = max(words, key=len)             # key=len picks by length, not alphabetically",
      "print(longest, len(longest))",
    ].join("\n"),
  }),
  P({
    slug: "regex-emails",
    title: "Extract Emails with Regex",
    category: "Strings",
    summary: "Pull email addresses out of free text.",
    stack: ["re"],
    code: [
      "import re                                                 # regular expression module",
      "",
      "text = \"Contact ada@example.com or bob@x.io for info.\"",
      "pattern = r\"[\\w.+-]+@[\\w-]+\\.[\\w.-]+\"             # raw string keeps backslashes literal",
      "emails = re.findall(pattern, text)                        # returns a list of all matches",
      "print(emails)                                             # ['ada@example.com','bob@x.io']",
    ].join("\n"),
  }),

  // ============================================================
  // LISTS / DICTS (31-40)
  // ============================================================
  P({
    slug: "list-comprehension",
    title: "List Comprehensions",
    category: "Lists & Dicts",
    summary: "Replace map/filter loops with one expression.",
    stack: ["comprehensions"],
    code: [
      "nums = range(1, 11)                                  # 1..10",
      "squares = [n * n for n in nums]                      # build a new list",
      "evens = [n for n in nums if n % 2 == 0]              # filter with `if`",
      "pairs = [(x, y) for x in range(3) for y in range(3)] # nested for = Cartesian product",
      "print(squares); print(evens); print(pairs)",
    ].join("\n"),
  }),
  P({
    slug: "dict-comprehension",
    title: "Dict Comprehensions",
    category: "Lists & Dicts",
    summary: "Build dicts inline like list comprehensions.",
    stack: ["comprehensions"],
    code: [
      "words = [\"apple\", \"pear\", \"banana\"]",
      "lengths = {w: len(w) for w in words}                 # key: value pair per iteration",
      "inverted = {v: k for k, v in lengths.items()}        # swap keys and values",
      "print(lengths); print(inverted)",
    ].join("\n"),
  }),
  P({
    slug: "flatten-list",
    title: "Flatten a Nested List",
    category: "Lists & Dicts",
    summary: "Turn a list-of-lists into a flat list.",
    stack: ["itertools"],
    code: [
      "from itertools import chain                          # chain.from_iterable is the idiom",
      "",
      "nested = [[1, 2], [3, 4, 5], [6]]",
      "flat = list(chain.from_iterable(nested))             # O(n) and lazy under the hood",
      "print(flat)                                          # [1,2,3,4,5,6]",
    ].join("\n"),
  }),
  P({
    slug: "group-by-key",
    title: "Group Items by Key",
    category: "Lists & Dicts",
    summary: "Bucket records into a dict of lists.",
    stack: ["defaultdict"],
    code: [
      "from collections import defaultdict                  # auto-creates the value on first access",
      "",
      "rows = [(\"fruit\", \"apple\"), (\"veg\", \"carrot\"), (\"fruit\", \"pear\")]",
      "groups = defaultdict(list)                            # missing key -> [] automatically",
      "for category, item in rows:                           # tuple-unpack each row",
      "    groups[category].append(item)                     # bucket the item",
      "print(dict(groups))                                   # cast back to plain dict for printing",
    ].join("\n"),
  }),
  P({
    slug: "merge-dicts",
    title: "Merge Two Dictionaries",
    category: "Lists & Dicts",
    summary: "Three idiomatic ways to combine dicts.",
    stack: ["dict"],
    code: [
      "a = {\"x\": 1, \"y\": 2}",
      "b = {\"y\": 20, \"z\": 30}",
      "print({**a, **b})        # 3.5+: unpack into a new dict; right side wins on conflict",
      "print(a | b)             # 3.9+: merge operator, same semantics",
      "c = a.copy(); c.update(b)# 2-step version that works on every Python version",
      "print(c)",
    ].join("\n"),
  }),
  P({
    slug: "remove-duplicates",
    title: "Remove Duplicates Preserving Order",
    category: "Lists & Dicts",
    summary: "Deduplicate without losing the original order.",
    stack: ["dict"],
    code: [
      "items = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3]",
      "# dict preserves insertion order since 3.7, and keys are unique:",
      "unique = list(dict.fromkeys(items))",
      "print(unique)                                       # [3,1,4,5,9,2,6]",
    ].join("\n"),
  }),
  P({
    slug: "matrix-transpose",
    title: "Transpose a Matrix",
    category: "Lists & Dicts",
    summary: "Swap rows and columns with zip().",
    stack: ["zip"],
    code: [
      "matrix = [[1, 2, 3], [4, 5, 6]]                     # 2 rows, 3 columns",
      "transposed = [list(row) for row in zip(*matrix)]    # *matrix unpacks rows as args",
      "print(transposed)                                   # [[1,4],[2,5],[3,6]]",
    ].join("\n"),
  }),
  P({
    slug: "sort-by-key",
    title: "Sort Records by a Field",
    category: "Lists & Dicts",
    summary: "Sort dicts by one of their values.",
    stack: ["sorted"],
    code: [
      "people = [",
      "    {\"name\": \"Ada\", \"age\": 36},",
      "    {\"name\": \"Bob\", \"age\": 25},",
      "    {\"name\": \"Cy\",  \"age\": 41},",
      "]",
      "by_age = sorted(people, key=lambda p: p[\"age\"])    # key fn extracts the sort field",
      "for p in by_age:                                       # already sorted ascending",
      "    print(p)",
    ].join("\n"),
  }),
  P({
    slug: "moving-average",
    title: "Moving Average",
    category: "Lists & Dicts",
    summary: "Smooth a list of numbers with a window.",
    stack: ["deque"],
    code: [
      "from collections import deque                      # O(1) appends + pops on both ends",
      "",
      "def moving_avg(data, k):                            # k = window size",
      "    window = deque(maxlen=k)                        # maxlen auto-drops the oldest",
      "    for x in data:",
      "        window.append(x)                            # slide the window forward",
      "        yield sum(window) / len(window)             # average of current window",
      "",
      "print(list(moving_avg([1, 2, 3, 4, 5, 6, 7], 3)))   # last value averages 5,6,7",
    ].join("\n"),
  }),
  P({
    slug: "two-sum",
    title: "Two Sum",
    category: "Lists & Dicts",
    summary: "Find two numbers that add to a target in O(n).",
    stack: ["hashmap"],
    code: [
      "def two_sum(nums, target):                # returns (i, j) or None",
      "    seen = {}                              # value -> index already visited",
      "    for i, n in enumerate(nums):           # one pass through the list",
      "        need = target - n                  # the complement we are looking for",
      "        if need in seen:                   # O(1) dict lookup",
      "            return seen[need], i           # earlier index first",
      "        seen[n] = i                        # remember current value",
      "    return None                            # no pair found",
      "",
      "print(two_sum([2, 7, 11, 15], 9))          # (0, 1)",
    ].join("\n"),
  }),

  // ============================================================
  // PATTERNS (41-50)
  // ============================================================
  P({
    slug: "pattern-square",
    title: "Solid Square Pattern",
    category: "Patterns",
    summary: "An n x n grid of stars.",
    stack: ["loops"],
    code: [
      "n = 5                                     # side length",
      "for i in range(n):                        # one row per i",
      "    print(\"* \" * n)                    # repeat the cell n times",
    ].join("\n"),
  }),
  P({
    slug: "pattern-right-triangle",
    title: "Right-Angle Triangle",
    category: "Patterns",
    summary: "Stars increase one per row.",
    stack: ["loops"],
    code: [
      "n = 5",
      "for i in range(1, n + 1):                # i = 1..n",
      "    print(\"*\" * i)                     # i stars on row i",
    ].join("\n"),
  }),
  P({
    slug: "pattern-inverted-triangle",
    title: "Inverted Triangle",
    category: "Patterns",
    summary: "Triangle that shrinks.",
    stack: ["loops"],
    code: [
      "n = 5",
      "for i in range(n, 0, -1):                # countdown from n to 1",
      "    print(\"*\" * i)",
    ].join("\n"),
  }),
  P({
    slug: "pattern-pyramid",
    title: "Centred Pyramid",
    category: "Patterns",
    summary: "Stars centred with spaces.",
    stack: ["loops"],
    code: [
      "n = 5                                       # number of rows",
      "for i in range(1, n + 1):                   # i = 1..n",
      "    spaces = \" \" * (n - i)               # leading spaces shrink each row",
      "    stars = \"*\" * (2 * i - 1)            # 1, 3, 5, 7 ... stars",
      "    print(spaces + stars)                   # one line of the pyramid",
    ].join("\n"),
  }),
  P({
    slug: "pattern-diamond",
    title: "Diamond Pattern",
    category: "Patterns",
    summary: "Pyramid + inverted pyramid stacked.",
    stack: ["loops"],
    code: [
      "n = 5",
      "for i in range(1, n + 1):                  # top half",
      "    print(\" \" * (n - i) + \"*\" * (2 * i - 1))",
      "for i in range(n - 1, 0, -1):              # bottom half",
      "    print(\" \" * (n - i) + \"*\" * (2 * i - 1))",
    ].join("\n"),
  }),
  P({
    slug: "pattern-hollow-square",
    title: "Hollow Square",
    category: "Patterns",
    summary: "Border-only square.",
    stack: ["loops"],
    code: [
      "n = 5",
      "for i in range(n):",
      "    if i == 0 or i == n - 1:               # first / last row: solid line",
      "        print(\"* \" * n)",
      "    else:                                   # middle rows: stars on edges only",
      "        print(\"* \" + \"  \" * (n - 2) + \"*\")",
    ].join("\n"),
  }),
  P({
    slug: "pattern-number-pyramid",
    title: "Number Pyramid",
    category: "Patterns",
    summary: "Each row prints 1..i.",
    stack: ["loops"],
    code: [
      "n = 5",
      "for i in range(1, n + 1):",
      "    row = \" \".join(str(j) for j in range(1, i + 1))  # '1 2 3 ...'",
      "    print(row.center(2 * n))                            # centre under the pyramid",
    ].join("\n"),
  }),
  P({
    slug: "pattern-floyd",
    title: "Floyd's Triangle",
    category: "Patterns",
    summary: "Consecutive integers in a triangle.",
    stack: ["loops"],
    code: [
      "n = 5                                  # number of rows",
      "num = 1                                # next number to print",
      "for i in range(1, n + 1):              # row i has i numbers",
      "    row = []",
      "    for _ in range(i):",
      "        row.append(str(num))           # add current number",
      "        num += 1                        # then advance",
      "    print(\" \".join(row))",
    ].join("\n"),
  }),
  P({
    slug: "pattern-pascal",
    title: "Pascal's Triangle",
    category: "Patterns",
    summary: "Each cell is the sum of the two above it.",
    stack: ["loops"],
    code: [
      "n = 6                                          # rows to print",
      "row = [1]                                       # row 0",
      "for r in range(n):",
      "    print(\" \".join(map(str, row)).center(2 * n * 2))  # centred display",
      "    row = [a + b for a, b in zip([0] + row, row + [0])]  # next row in one line",
    ].join("\n"),
  }),
  P({
    slug: "pattern-checkerboard",
    title: "Checkerboard",
    category: "Patterns",
    summary: "Alternating # and . cells.",
    stack: ["loops"],
    code: [
      "n = 8                                            # board side",
      "for r in range(n):",
      "    row = \"\"                                  # build one row of text",
      "    for c in range(n):",
      "        row += \"# \" if (r + c) % 2 == 0 else \". \"  # parity flips per cell",
      "    print(row)",
    ].join("\n"),
  }),

  // ============================================================
  // GAMES (51-60)
  // ============================================================
  P({
    slug: "game-guess-number",
    title: "Guess the Number",
    category: "Games",
    summary: "Computer picks 1-100, you guess.",
    stack: ["random"],
    code: [
      "import random                                  # PRNG",
      "secret = random.randint(1, 100)                # inclusive on both ends",
      "tries = 0                                       # count attempts",
      "while True:                                     # loop until break",
      "    guess = int(input(\"guess (1-100): \"))  # cast str -> int",
      "    tries += 1",
      "    if guess < secret:",
      "        print(\"higher\")",
      "    elif guess > secret:",
      "        print(\"lower\")",
      "    else:",
      "        print(f\"Got it in {tries} tries!\")",
      "        break                                  # exit the while loop",
    ].join("\n"),
  }),
  P({
    slug: "game-rps",
    title: "Rock, Paper, Scissors",
    category: "Games",
    summary: "One round against the computer.",
    stack: ["random"],
    code: [
      "import random",
      "moves = [\"rock\", \"paper\", \"scissors\"]                    # legal moves",
      "beats = {\"rock\": \"scissors\", \"paper\": \"rock\", \"scissors\": \"paper\"}  # key beats value",
      "you = input(\"rock / paper / scissors: \").strip().lower()    # normalise input",
      "cpu = random.choice(moves)                                     # pick uniformly at random",
      "print(\"computer chose\", cpu)",
      "if you == cpu:                                                 # tie",
      "    print(\"draw\")",
      "elif beats.get(you) == cpu:                                    # your move beats cpu's",
      "    print(\"you win!\")",
      "else:                                                          # otherwise computer wins",
      "    print(\"you lose\")",
    ].join("\n"),
  }),
  P({
    slug: "game-coin-flip",
    title: "Coin Flip Simulator",
    category: "Games",
    summary: "Flip n times and report frequencies.",
    stack: ["random"],
    code: [
      "import random",
      "from collections import Counter",
      "flips = [random.choice([\"H\", \"T\"]) for _ in range(1000)]   # 1000 fair flips",
      "print(Counter(flips))                                           # Counter({'H':..., 'T':...})",
    ].join("\n"),
  }),
  P({
    slug: "game-dice-roll",
    title: "Dice Roll Histogram",
    category: "Games",
    summary: "Two six-sided dice and frequency bar chart.",
    stack: ["random"],
    code: [
      "import random",
      "rolls = [random.randint(1, 6) + random.randint(1, 6) for _ in range(2000)]",
      "counts = {x: rolls.count(x) for x in range(2, 13)}            # tally each total",
      "for total, n in counts.items():                                # ASCII histogram",
      "    print(f\"{total:>2}: {'#' * (n // 20)}\")",
    ].join("\n"),
  }),
  P({
    slug: "game-hangman",
    title: "Hangman",
    category: "Games",
    summary: "Guess the word one letter at a time.",
    stack: ["random"],
    code: [
      "import random",
      "WORDS = [\"python\", \"hangman\", \"developer\", \"keyboard\"]   # word bank",
      "word = random.choice(WORDS)                                    # secret",
      "guessed = set()                                                # letters already tried",
      "lives = 6                                                      # wrong guesses allowed",
      "while lives > 0:                                               # main loop",
      "    display = \"\".join(c if c in guessed else \"_\" for c in word)",
      "    print(display, f\"lives={lives}\")",
      "    if \"_\" not in display:                                  # all letters revealed",
      "        print(\"You win!\"); break",
      "    g = input(\"letter: \").lower()                           # one char at a time",
      "    if g in guessed:                                           # ignore duplicates",
      "        continue",
      "    guessed.add(g)",
      "    if g not in word:                                          # wrong guess costs a life",
      "        lives -= 1",
      "else:                                                          # while-else runs when condition becomes False",
      "    print(\"Out of lives. Word was\", word)",
    ].join("\n"),
  }),
  P({
    slug: "game-tic-tac-toe",
    title: "Tic-Tac-Toe (2 Player)",
    category: "Games",
    summary: "Hot-seat 3x3 with win detection.",
    stack: ["lists"],
    code: [
      "board = [\" \"] * 9                              # flat 3x3 grid",
      "WINS = [(0,1,2),(3,4,5),(6,7,8),(0,3,6),(1,4,7),(2,5,8),(0,4,8),(2,4,6)]",
      "",
      "def show():                                       # print the board",
      "    for r in range(3):",
      "        print(\"|\".join(board[r*3:(r+1)*3]))",
      "        if r < 2: print(\"-+-+-\")",
      "",
      "def winner():                                     # X / O / None",
      "    for a,b,c in WINS:",
      "        if board[a] == board[b] == board[c] != \" \":",
      "            return board[a]",
      "    return None",
      "",
      "turn = \"X\"                                      # X starts",
      "for _ in range(9):                                # at most 9 moves",
      "    show()",
      "    i = int(input(f\"{turn} pos 0-8: \"))",
      "    if board[i] != \" \":                        # cell taken",
      "        print(\"taken\"); continue",
      "    board[i] = turn",
      "    if winner():",
      "        show(); print(turn, \"wins\"); break",
      "    turn = \"O\" if turn == \"X\" else \"X\"   # swap player",
      "else:",
      "    print(\"draw\")                              # for-else: no break => draw",
    ].join("\n"),
  }),
  P({
    slug: "game-number-guess-binary",
    title: "Computer Guesses Your Number",
    category: "Games",
    summary: "Binary search where the computer is the guesser.",
    stack: ["binary-search"],
    code: [
      "lo, hi = 1, 100                                  # search range",
      "print(\"Pick a number 1-100, I'll guess.\")",
      "while lo <= hi:                                  # standard binary-search loop",
      "    mid = (lo + hi) // 2                          # midpoint",
      "    ans = input(f\"is it {mid}? (h/l/=) \")",
      "    if ans == \"=\": print(\"got it!\"); break # correct",
      "    elif ans == \"h\": lo = mid + 1             # secret is higher",
      "    else: hi = mid - 1                            # secret is lower",
    ].join("\n"),
  }),
  P({
    slug: "game-mad-libs",
    title: "Mad Libs",
    category: "Games",
    summary: "Fill in the blanks story generator.",
    stack: ["f-string"],
    code: [
      "noun = input(\"a noun: \")",
      "verb = input(\"a verb: \")",
      "adj  = input(\"an adjective: \")",
      "print(f\"The {adj} {noun} loves to {verb} every morning.\")",
    ].join("\n"),
  }),
  P({
    slug: "game-fizzbuzz",
    title: "FizzBuzz",
    category: "Games",
    summary: "The classic interview warm-up.",
    stack: ["loops"],
    code: [
      "for n in range(1, 31):",
      "    if n % 15 == 0:                       # divisible by both 3 and 5",
      "        print(\"FizzBuzz\")",
      "    elif n % 3 == 0:",
      "        print(\"Fizz\")",
      "    elif n % 5 == 0:",
      "        print(\"Buzz\")",
      "    else:",
      "        print(n)",
    ].join("\n"),
  }),
  P({
    slug: "game-snake-text",
    title: "Snake (Text Frame)",
    category: "Games",
    summary: "One step of a text-mode snake game.",
    stack: ["game-loop"],
    code: [
      "# Renders one frame of a snake on a 10x10 grid (no real-time input).",
      "W, H = 10, 10                                  # board size",
      "snake = [(5, 5), (5, 4), (5, 3)]               # head first; cells (row, col)",
      "food = (2, 7)",
      "for r in range(H):",
      "    row = \"\"",
      "    for c in range(W):",
      "        if (r, c) == snake[0]: row += \"O\"   # head",
      "        elif (r, c) in snake[1:]: row += \"o\"# body",
      "        elif (r, c) == food: row += \"*\"    # food",
      "        else: row += \".\"",
      "    print(row)",
    ].join("\n"),
  }),

  // ============================================================
  // ALGORITHMS (61-70)
  // ============================================================
  P({
    slug: "bubble-sort",
    title: "Bubble Sort",
    category: "Algorithms",
    summary: "Easiest sort to understand; O(n^2).",
    stack: ["sorting"],
    code: [
      "def bubble_sort(arr):                       # sorts in place and returns the list",
      "    n = len(arr)",
      "    for i in range(n):                       # n passes are always enough",
      "        swapped = False                      # short-circuit if already sorted",
      "        for j in range(n - 1 - i):           # last i items are already in place",
      "            if arr[j] > arr[j + 1]:          # out of order -> swap",
      "                arr[j], arr[j + 1] = arr[j + 1], arr[j]",
      "                swapped = True",
      "        if not swapped:                      # no swaps -> sorted, exit early",
      "            break",
      "    return arr",
      "",
      "print(bubble_sort([5, 2, 9, 1, 7]))",
    ].join("\n"),
  }),
  P({
    slug: "selection-sort",
    title: "Selection Sort",
    category: "Algorithms",
    summary: "Repeatedly pick the smallest remaining element.",
    stack: ["sorting"],
    code: [
      "def selection_sort(arr):",
      "    for i in range(len(arr)):                # position to fill",
      "        m = i                                 # assume i holds the min",
      "        for j in range(i + 1, len(arr)):     # scan the unsorted tail",
      "            if arr[j] < arr[m]:               # found a smaller value",
      "                m = j",
      "        arr[i], arr[m] = arr[m], arr[i]      # swap min into place",
      "    return arr",
      "",
      "print(selection_sort([5, 2, 9, 1, 7]))",
    ].join("\n"),
  }),
  P({
    slug: "insertion-sort",
    title: "Insertion Sort",
    category: "Algorithms",
    summary: "Build the sorted list one element at a time.",
    stack: ["sorting"],
    code: [
      "def insertion_sort(arr):",
      "    for i in range(1, len(arr)):              # arr[0:i] is the sorted prefix",
      "        x = arr[i]                             # element to insert",
      "        j = i - 1",
      "        while j >= 0 and arr[j] > x:           # shift larger elements right",
      "            arr[j + 1] = arr[j]",
      "            j -= 1",
      "        arr[j + 1] = x                         # drop x into the gap",
      "    return arr",
      "",
      "print(insertion_sort([5, 2, 9, 1, 7]))",
    ].join("\n"),
  }),
  P({
    slug: "merge-sort",
    title: "Merge Sort",
    category: "Algorithms",
    summary: "Divide and conquer, O(n log n).",
    stack: ["sorting"],
    code: [
      "def merge_sort(a):",
      "    if len(a) <= 1: return a                  # base case",
      "    mid = len(a) // 2                          # split point",
      "    left = merge_sort(a[:mid])                 # sort halves recursively",
      "    right = merge_sort(a[mid:])",
      "    out, i, j = [], 0, 0                       # merge two sorted halves",
      "    while i < len(left) and j < len(right):",
      "        if left[i] <= right[j]:",
      "            out.append(left[i]); i += 1",
      "        else:",
      "            out.append(right[j]); j += 1",
      "    out.extend(left[i:]); out.extend(right[j:])# append remainder",
      "    return out",
      "",
      "print(merge_sort([5, 2, 9, 1, 7, 3]))",
    ].join("\n"),
  }),
  P({
    slug: "quick-sort",
    title: "Quick Sort",
    category: "Algorithms",
    summary: "Lomuto partition variant.",
    stack: ["sorting"],
    code: [
      "def quick_sort(a):",
      "    if len(a) <= 1: return a                  # base case",
      "    pivot = a[len(a) // 2]                     # pick a middle pivot to avoid worst case on sorted input",
      "    less    = [x for x in a if x < pivot]      # partition into 3 buckets",
      "    equal   = [x for x in a if x == pivot]",
      "    greater = [x for x in a if x > pivot]",
      "    return quick_sort(less) + equal + quick_sort(greater)",
      "",
      "print(quick_sort([5, 2, 9, 1, 7, 3, 5]))",
    ].join("\n"),
  }),
  P({
    slug: "binary-search",
    title: "Binary Search",
    category: "Algorithms",
    summary: "Find a value in a sorted list in O(log n).",
    stack: ["search"],
    code: [
      "def bsearch(arr, target):                    # arr MUST be sorted ascending",
      "    lo, hi = 0, len(arr) - 1                  # inclusive bounds",
      "    while lo <= hi:                           # standard loop invariant",
      "        mid = (lo + hi) // 2",
      "        if arr[mid] == target: return mid     # found",
      "        if arr[mid] < target: lo = mid + 1    # search right half",
      "        else: hi = mid - 1                    # search left half",
      "    return -1                                 # not present",
      "",
      "print(bsearch([1, 3, 5, 7, 9, 11], 7))        # 3",
    ].join("\n"),
  }),
  P({
    slug: "linear-search",
    title: "Linear Search",
    category: "Algorithms",
    summary: "Walk the list one element at a time.",
    stack: ["search"],
    code: [
      "def lsearch(arr, target):",
      "    for i, x in enumerate(arr):              # enumerate gives both index and value",
      "        if x == target:",
      "            return i                          # first match",
      "    return -1",
      "",
      "print(lsearch([\"a\", \"b\", \"c\"], \"b\"))",
    ].join("\n"),
  }),
  P({
    slug: "kadane",
    title: "Maximum Subarray (Kadane)",
    category: "Algorithms",
    summary: "Largest contiguous sum in O(n).",
    stack: ["dp"],
    code: [
      "def max_subarray(a):",
      "    best = cur = a[0]                         # both start at the first element",
      "    for x in a[1:]:",
      "        cur = max(x, cur + x)                  # extend or restart",
      "        best = max(best, cur)                  # track global max",
      "    return best",
      "",
      "print(max_subarray([-2, 1, -3, 4, -1, 2, 1, -5, 4]))   # 6",
    ].join("\n"),
  }),
  P({
    slug: "coin-change-greedy",
    title: "Coin Change (Greedy)",
    category: "Algorithms",
    summary: "Fewest coins for canonical denominations.",
    stack: ["greedy"],
    code: [
      "def change(amount, coins=(25, 10, 5, 1)):    # US coins are canonical",
      "    result = {}",
      "    for c in coins:                           # largest first",
      "        n, amount = divmod(amount, c)         # how many fit, what is left",
      "        if n: result[c] = n",
      "    return result",
      "",
      "print(change(87))                             # {25:3, 10:1, 1:2}",
    ].join("\n"),
  }),
  P({
    slug: "knapsack-dp",
    title: "0/1 Knapsack",
    category: "Algorithms",
    summary: "Classic DP problem.",
    stack: ["dp"],
    code: [
      "def knapsack(weights, values, W):                 # W = capacity",
      "    n = len(weights)",
      "    dp = [[0] * (W + 1) for _ in range(n + 1)]    # dp[i][w] = best with first i items, cap w",
      "    for i in range(1, n + 1):",
      "        for w in range(W + 1):",
      "            dp[i][w] = dp[i-1][w]                  # skip item i",
      "            if weights[i-1] <= w:                  # can we fit it?",
      "                dp[i][w] = max(dp[i][w], dp[i-1][w - weights[i-1]] + values[i-1])",
      "    return dp[n][W]",
      "",
      "print(knapsack([2,3,4,5], [3,4,5,6], 5))           # 7",
    ].join("\n"),
  }),

  // ============================================================
  // DATA STRUCTURES (71-80)
  // ============================================================
  P({
    slug: "stack-impl",
    title: "Stack from a List",
    category: "Data Structures",
    summary: "LIFO with append/pop.",
    stack: ["list"],
    code: [
      "stack = []                       # empty stack",
      "stack.append(1)                  # push",
      "stack.append(2)",
      "stack.append(3)",
      "print(stack.pop())               # pop -> 3 (LIFO)",
      "print(stack)                     # [1, 2]",
    ].join("\n"),
  }),
  P({
    slug: "queue-impl",
    title: "Queue with deque",
    category: "Data Structures",
    summary: "FIFO with O(1) ends.",
    stack: ["deque"],
    code: [
      "from collections import deque",
      "q = deque()",
      "q.append(\"a\")                  # enqueue right",
      "q.append(\"b\")",
      "q.append(\"c\")",
      "print(q.popleft())                # dequeue left -> 'a' (FIFO)",
      "print(q)",
    ].join("\n"),
  }),
  P({
    slug: "linked-list",
    title: "Singly Linked List",
    category: "Data Structures",
    summary: "Minimal Node + LinkedList class.",
    stack: ["class"],
    code: [
      "class Node:                                 # one cell of the list",
      "    def __init__(self, value):",
      "        self.value = value                  # payload",
      "        self.next = None                    # pointer to next node",
      "",
      "class LinkedList:",
      "    def __init__(self): self.head = None    # empty list has no head",
      "    def push_front(self, v):                 # O(1) insert at head",
      "        n = Node(v); n.next = self.head; self.head = n",
      "    def __iter__(self):                      # let `for x in ll` work",
      "        cur = self.head",
      "        while cur:                           # walk until we reach None",
      "            yield cur.value",
      "            cur = cur.next",
      "",
      "ll = LinkedList()",
      "for x in [3, 2, 1]: ll.push_front(x)        # head=1, 2, 3",
      "print(list(ll))                              # [1, 2, 3]",
    ].join("\n"),
  }),
  P({
    slug: "binary-tree",
    title: "Binary Tree Traversal",
    category: "Data Structures",
    summary: "Pre/in/post-order with recursion.",
    stack: ["tree"],
    code: [
      "class Node:",
      "    def __init__(self, v, l=None, r=None):",
      "        self.v, self.l, self.r = v, l, r",
      "",
      "root = Node(1, Node(2, Node(4), Node(5)), Node(3))   # hand-built tree",
      "",
      "def inorder(n):                              # left, root, right",
      "    if not n: return",
      "    inorder(n.l); print(n.v, end=\" \"); inorder(n.r)",
      "",
      "inorder(root)                                # 4 2 5 1 3",
      "print()",
    ].join("\n"),
  }),
  P({
    slug: "bst",
    title: "Binary Search Tree",
    category: "Data Structures",
    summary: "Insert + search keeping BST invariant.",
    stack: ["tree"],
    code: [
      "class BST:",
      "    def __init__(self): self.root = None",
      "    def insert(self, v):",
      "        def _ins(n, v):",
      "            if n is None: return {\"v\": v, \"l\": None, \"r\": None}  # leaf",
      "            if v < n[\"v\"]: n[\"l\"] = _ins(n[\"l\"], v)              # go left",
      "            else:           n[\"r\"] = _ins(n[\"r\"], v)              # go right (or equal)",
      "            return n",
      "        self.root = _ins(self.root, v)",
      "    def __contains__(self, v):                  # enables: v in tree",
      "        n = self.root",
      "        while n:",
      "            if v == n[\"v\"]: return True",
      "            n = n[\"l\"] if v < n[\"v\"] else n[\"r\"]",
      "        return False",
      "",
      "t = BST()",
      "for x in [5, 3, 8, 1, 4]: t.insert(x)",
      "print(4 in t, 9 in t)                            # True False",
    ].join("\n"),
  }),
  P({
    slug: "graph-bfs",
    title: "Graph BFS",
    category: "Data Structures",
    summary: "Shortest unweighted path layer by layer.",
    stack: ["queue"],
    code: [
      "from collections import deque",
      "graph = {\"A\":[\"B\",\"C\"], \"B\":[\"D\"], \"C\":[\"D\",\"E\"], \"D\":[], \"E\":[]}",
      "",
      "def bfs(start):",
      "    seen = {start}                            # set of visited nodes",
      "    q = deque([start])                        # FIFO frontier",
      "    while q:                                  # while there are nodes to visit",
      "        n = q.popleft()",
      "        print(n, end=\" \")",
      "        for nb in graph[n]:                   # enqueue unseen neighbours",
      "            if nb not in seen:",
      "                seen.add(nb); q.append(nb)",
      "    print()",
      "",
      "bfs(\"A\")                                    # A B C D E",
    ].join("\n"),
  }),
  P({
    slug: "graph-dfs",
    title: "Graph DFS (Recursive)",
    category: "Data Structures",
    summary: "Depth-first traversal of a graph.",
    stack: ["recursion"],
    code: [
      "graph = {\"A\":[\"B\",\"C\"], \"B\":[\"D\"], \"C\":[\"D\",\"E\"], \"D\":[], \"E\":[]}",
      "seen = set()",
      "def dfs(n):",
      "    if n in seen: return                     # avoid revisits / cycles",
      "    seen.add(n)",
      "    print(n, end=\" \")",
      "    for nb in graph[n]: dfs(nb)              # recurse into neighbours",
      "",
      "dfs(\"A\"); print()                          # A B D C E",
    ].join("\n"),
  }),
  P({
    slug: "heap-topk",
    title: "Top-K with a Heap",
    category: "Data Structures",
    summary: "Largest K values in O(n log k).",
    stack: ["heapq"],
    code: [
      "import heapq                                 # min-heap implementation",
      "data = [9, 1, 7, 3, 5, 8, 2, 6, 4]",
      "print(heapq.nlargest(3, data))               # [9, 8, 7]",
      "print(heapq.nsmallest(3, data))              # [1, 2, 3]",
    ].join("\n"),
  }),
  P({
    slug: "trie",
    title: "Trie (Prefix Tree)",
    category: "Data Structures",
    summary: "Insert words and test prefixes.",
    stack: ["dict"],
    code: [
      "class Trie:",
      "    def __init__(self): self.root = {}        # nested dict",
      "    def insert(self, word):",
      "        node = self.root",
      "        for ch in word:",
      "            node = node.setdefault(ch, {})    # create child if missing",
      "        node[\"$\"] = True                    # end-of-word marker",
      "    def starts_with(self, prefix):",
      "        node = self.root",
      "        for ch in prefix:",
      "            if ch not in node: return False",
      "            node = node[ch]",
      "        return True",
      "",
      "t = Trie()",
      "for w in [\"car\", \"cat\", \"cart\"]: t.insert(w)",
      "print(t.starts_with(\"car\"), t.starts_with(\"dog\"))",
    ].join("\n"),
  }),
  P({
    slug: "lru-cache",
    title: "LRU Cache",
    category: "Data Structures",
    summary: "Tiny LRU using OrderedDict.",
    stack: ["OrderedDict"],
    code: [
      "from collections import OrderedDict",
      "",
      "class LRU:",
      "    def __init__(self, capacity):",
      "        self.cap = capacity",
      "        self.data = OrderedDict()             # remembers insertion order",
      "    def get(self, k):",
      "        if k not in self.data: return None",
      "        self.data.move_to_end(k)              # mark as most recently used",
      "        return self.data[k]",
      "    def put(self, k, v):",
      "        if k in self.data: self.data.move_to_end(k)",
      "        self.data[k] = v",
      "        if len(self.data) > self.cap:",
      "            self.data.popitem(last=False)     # evict least recently used",
      "",
      "c = LRU(2)",
      "c.put(\"a\", 1); c.put(\"b\", 2); c.get(\"a\"); c.put(\"c\", 3)",
      "print(list(c.data))                            # ['a','c']  -- 'b' was evicted",
    ].join("\n"),
  }),

  // ============================================================
  // FILES / UTILITIES (81-90)
  // ============================================================
  P({
    slug: "file-write-read",
    title: "Write and Read a File",
    category: "Files & Utilities",
    summary: "Round-trip text through the filesystem.",
    stack: ["open"],
    code: [
      "with open(\"/tmp/demo.txt\", \"w\", encoding=\"utf-8\") as f:  # 'w' truncates",
      "    f.write(\"Hello, file!\\n\")                              # write text + newline",
      "",
      "with open(\"/tmp/demo.txt\", \"r\", encoding=\"utf-8\") as f:  # 'r' is the default",
      "    print(f.read())                                            # read entire content",
    ].join("\n"),
  }),
  P({
    slug: "csv-rows",
    title: "Read and Write CSV",
    category: "Files & Utilities",
    summary: "Round-trip a list of dicts through CSV.",
    stack: ["csv"],
    code: [
      "import csv, io                              # io.StringIO simulates a file in memory",
      "",
      "rows = [{\"name\":\"Ada\",\"age\":36}, {\"name\":\"Bob\",\"age\":25}]",
      "buf = io.StringIO()                          # write target",
      "writer = csv.DictWriter(buf, fieldnames=[\"name\",\"age\"])",
      "writer.writeheader(); writer.writerows(rows)",
      "print(buf.getvalue())                        # the CSV text",
      "",
      "buf.seek(0)                                   # rewind for reading",
      "for row in csv.DictReader(buf):              # parse back into dicts",
      "    print(row)",
    ].join("\n"),
  }),
  P({
    slug: "json-roundtrip",
    title: "JSON Serialise / Deserialise",
    category: "Files & Utilities",
    summary: "Convert Python objects to JSON and back.",
    stack: ["json"],
    code: [
      "import json",
      "data = {\"name\": \"Ada\", \"skills\": [\"python\", \"haskell\"]}",
      "encoded = json.dumps(data, indent=2)         # pretty-print",
      "print(encoded)",
      "decoded = json.loads(encoded)                 # parse back",
      "print(decoded[\"skills\"][0])",
    ].join("\n"),
  }),
  P({
    slug: "datetime-basics",
    title: "Dates and Times",
    category: "Files & Utilities",
    summary: "Now, format, parse, arithmetic.",
    stack: ["datetime"],
    code: [
      "from datetime import datetime, timedelta",
      "now = datetime.now()                          # local time, no tz info",
      "print(now.isoformat())                        # ISO-8601",
      "tomorrow = now + timedelta(days=1)            # add a duration",
      "print(tomorrow.strftime(\"%Y-%m-%d\"))      # custom format",
      "parsed = datetime.strptime(\"2024-01-31\", \"%Y-%m-%d\")  # parse from text",
      "print(parsed)",
    ].join("\n"),
  }),
  P({
    slug: "uuid-tokens",
    title: "Generate UUID Tokens",
    category: "Files & Utilities",
    summary: "Random unique identifiers.",
    stack: ["uuid"],
    code: [
      "import uuid",
      "print(uuid.uuid4())                           # random 128-bit id",
      "print(uuid.uuid4().hex)                       # hex without dashes",
    ].join("\n"),
  }),
  P({
    slug: "hash-password",
    title: "Hash a Password (PBKDF2)",
    category: "Files & Utilities",
    summary: "Salted, slow hashing with stdlib only.",
    stack: ["hashlib", "secrets"],
    code: [
      "import hashlib, secrets",
      "",
      "salt = secrets.token_bytes(16)                            # fresh random salt",
      "pw = b\"correct horse battery staple\"                    # password bytes",
      "digest = hashlib.pbkdf2_hmac(\"sha256\", pw, salt, 200_000)# 200k iterations",
      "print(salt.hex(), digest.hex())                            # store salt + digest, never the password",
    ].join("\n"),
  }),
  P({
    slug: "env-config",
    title: "Read Environment Variables",
    category: "Files & Utilities",
    summary: "Safe config loading with defaults.",
    stack: ["os"],
    code: [
      "import os",
      "debug = os.environ.get(\"DEBUG\", \"0\") == \"1\"   # default to off",
      "port = int(os.environ.get(\"PORT\", \"8000\"))         # cast to int",
      "print(\"debug:\", debug, \"port:\", port)",
    ].join("\n"),
  }),
  P({
    slug: "tempfile-demo",
    title: "Temporary Files",
    category: "Files & Utilities",
    summary: "Auto-cleaned scratch files.",
    stack: ["tempfile"],
    code: [
      "import tempfile, os",
      "with tempfile.NamedTemporaryFile(mode=\"w+\", delete=True) as f:",
      "    f.write(\"scratch\\n\"); f.flush()      # write and ensure data hits disk",
      "    print(\"path:\", f.name)                 # OS picks a unique path",
      "    f.seek(0); print(\"read:\", f.read())   # read back what we wrote",
      "# file is removed here automatically",
    ].join("\n"),
  }),
  P({
    slug: "subprocess-echo",
    title: "Run a Shell Command",
    category: "Files & Utilities",
    summary: "Call out to the OS safely.",
    stack: ["subprocess"],
    code: [
      "import subprocess",
      "result = subprocess.run([\"echo\", \"hello\"], capture_output=True, text=True)",
      "print(\"stdout:\", result.stdout.strip())   # captured stdout",
      "print(\"code:\", result.returncode)         # 0 means success",
    ].join("\n"),
  }),
  P({
    slug: "argparse-cli",
    title: "Command-line Interface",
    category: "Files & Utilities",
    summary: "Parse flags and positional args.",
    stack: ["argparse"],
    code: [
      "import argparse, sys",
      "parser = argparse.ArgumentParser(description=\"greet someone\")",
      "parser.add_argument(\"name\")                                   # positional, required",
      "parser.add_argument(\"--shout\", action=\"store_true\")         # boolean flag",
      "args = parser.parse_args([\"Ada\", \"--shout\"])               # parse a fake CLI",
      "msg = f\"Hello, {args.name}!\"",
      "print(msg.upper() if args.shout else msg)",
    ].join("\n"),
  }),

  // ============================================================
  // OOP / FUNCTIONAL / MISC (91-105)
  // ============================================================
  P({
    slug: "class-bank-account",
    title: "Class: Bank Account",
    category: "OOP",
    summary: "Encapsulation with deposit, withdraw, balance.",
    stack: ["class"],
    code: [
      "class Account:",
      "    def __init__(self, owner, balance=0):",
      "        self.owner = owner                  # public attribute",
      "        self._balance = balance             # underscore = convention for 'internal'",
      "    def deposit(self, amount):",
      "        if amount <= 0: raise ValueError(\"positive only\")",
      "        self._balance += amount",
      "    def withdraw(self, amount):",
      "        if amount > self._balance: raise ValueError(\"insufficient funds\")",
      "        self._balance -= amount",
      "    @property                                # access like an attribute",
      "    def balance(self): return self._balance",
      "",
      "a = Account(\"Ada\", 100)",
      "a.deposit(50); a.withdraw(30)",
      "print(a.owner, a.balance)                    # Ada 120",
    ].join("\n"),
  }),
  P({
    slug: "inheritance-shapes",
    title: "Inheritance: Shapes",
    category: "OOP",
    summary: "Polymorphism via a common base class.",
    stack: ["inheritance"],
    code: [
      "import math",
      "",
      "class Shape:                                   # base / abstract",
      "    def area(self): raise NotImplementedError # subclasses must override",
      "",
      "class Circle(Shape):                           # 'extends' Shape",
      "    def __init__(self, r): self.r = r",
      "    def area(self): return math.pi * self.r ** 2",
      "",
      "class Rect(Shape):",
      "    def __init__(self, w, h): self.w, self.h = w, h",
      "    def area(self): return self.w * self.h",
      "",
      "for s in [Circle(2), Rect(3, 4)]:              # polymorphic call",
      "    print(type(s).__name__, round(s.area(), 2))",
    ].join("\n"),
  }),
  P({
    slug: "dataclass-point",
    title: "@dataclass Point",
    category: "OOP",
    summary: "Auto-generated __init__, __repr__, __eq__.",
    stack: ["dataclasses"],
    code: [
      "from dataclasses import dataclass",
      "",
      "@dataclass                                     # decorator generates boilerplate",
      "class Point:",
      "    x: float                                    # type-annotated fields become __init__ params",
      "    y: float",
      "",
      "a = Point(1, 2)",
      "b = Point(1, 2)",
      "print(a)                                        # Point(x=1, y=2) -- nice __repr__",
      "print(a == b)                                   # True -- structural equality",
    ].join("\n"),
  }),
  P({
    slug: "enum-status",
    title: "Enums for Status",
    category: "OOP",
    summary: "Type-safe constants.",
    stack: ["enum"],
    code: [
      "from enum import Enum",
      "",
      "class Status(Enum):",
      "    OPEN = \"open\"                              # name + value pair",
      "    CLOSED = \"closed\"",
      "    PENDING = \"pending\"",
      "",
      "s = Status.OPEN",
      "print(s.name, s.value)                          # OPEN open",
      "print(s is Status.OPEN)                         # identity comparison is safe",
    ].join("\n"),
  }),
  P({
    slug: "generator-fib",
    title: "Generator: Infinite Fibonacci",
    category: "Functional",
    summary: "Yield values lazily, forever.",
    stack: ["yield"],
    code: [
      "def fib():                                   # infinite generator",
      "    a, b = 0, 1",
      "    while True:                              # never raises StopIteration",
      "        yield a                              # pause and emit a",
      "        a, b = b, a + b                      # advance",
      "",
      "from itertools import islice",
      "print(list(islice(fib(), 10)))               # take first 10 values safely",
    ].join("\n"),
  }),
  P({
    slug: "decorator-timer",
    title: "Decorator: Timing",
    category: "Functional",
    summary: "Measure how long a function takes.",
    stack: ["functools"],
    code: [
      "import time, functools",
      "",
      "def timed(fn):                               # decorator factory",
      "    @functools.wraps(fn)                     # keeps fn's name / docstring",
      "    def wrapper(*args, **kw):                # accept any call signature",
      "        t0 = time.perf_counter()             # high-res clock",
      "        result = fn(*args, **kw)",
      "        print(f\"{fn.__name__} took {time.perf_counter()-t0:.4f}s\")",
      "        return result",
      "    return wrapper",
      "",
      "@timed                                        # equivalent to slow = timed(slow)",
      "def slow():",
      "    time.sleep(0.05)                          # pretend to do work",
      "",
      "slow()",
    ].join("\n"),
  }),
  P({
    slug: "context-manager",
    title: "Custom Context Manager",
    category: "Functional",
    summary: "Use `with` for setup/teardown.",
    stack: ["contextlib"],
    code: [
      "from contextlib import contextmanager",
      "",
      "@contextmanager                              # turns a generator into a context manager",
      "def tag(name):",
      "    print(f\"<{name}>\")                     # setup runs before the `with` body",
      "    try:",
      "        yield                                # control passes to the `with` block",
      "    finally:",
      "        print(f\"</{name}>\")                # teardown runs even on exception",
      "",
      "with tag(\"h1\"):",
      "    print(\"Hello\")",
    ].join("\n"),
  }),
  P({
    slug: "map-filter-reduce",
    title: "map / filter / reduce",
    category: "Functional",
    summary: "Classic functional trio.",
    stack: ["functools"],
    code: [
      "from functools import reduce",
      "nums = [1, 2, 3, 4, 5]",
      "doubled  = list(map(lambda x: x * 2, nums))    # apply fn to every element",
      "evens    = list(filter(lambda x: x % 2 == 0, nums))",
      "total    = reduce(lambda a, b: a + b, nums, 0) # fold into a single value (init=0)",
      "print(doubled, evens, total)",
    ].join("\n"),
  }),
  P({
    slug: "memoize-cache",
    title: "Memoization with lru_cache",
    category: "Functional",
    summary: "Speed up pure functions transparently.",
    stack: ["functools"],
    code: [
      "from functools import lru_cache",
      "",
      "@lru_cache(maxsize=None)                     # remember every (args) -> result",
      "def fib(n):                                  # naive recursion becomes fast",
      "    return n if n < 2 else fib(n - 1) + fib(n - 2)",
      "",
      "print(fib(50))                               # would be unbearable without cache",
      "print(fib.cache_info())                      # hits / misses / current size",
    ].join("\n"),
  }),
  P({
    slug: "exception-handling",
    title: "Exception Handling",
    category: "Misc",
    summary: "try/except/else/finally with custom exceptions.",
    stack: ["exceptions"],
    code: [
      "class NotFoundError(Exception):                # custom exception type",
      "    pass",
      "",
      "def lookup(d, k):",
      "    try:",
      "        return d[k]                            # may raise KeyError",
      "    except KeyError as e:                      # catch + re-raise as our type",
      "        raise NotFoundError(f\"missing key {k}\") from e",
      "    finally:",
      "        print(\"lookup attempted\")           # always runs",
      "",
      "try:",
      "    lookup({\"a\": 1}, \"b\")",
      "except NotFoundError as e:",
      "    print(\"caught:\", e)",
    ].join("\n"),
  }),
  P({
    slug: "regex-validate",
    title: "Validate with Regex",
    category: "Misc",
    summary: "Reusable patterns for emails and phones.",
    stack: ["re"],
    code: [
      "import re",
      "EMAIL = re.compile(r\"^[\\w.+-]+@[\\w-]+\\.[\\w.-]+$\")     # ^/$ anchor full string",
      "PHONE = re.compile(r\"^\\+?\\d{7,15}$\")                     # +123456789 etc",
      "",
      "print(bool(EMAIL.match(\"ada@x.io\")))                       # True",
      "print(bool(PHONE.match(\"+15551234567\")))                    # True",
      "print(bool(EMAIL.match(\"nope\")))                            # False",
    ].join("\n"),
  }),
  P({
    slug: "threading-counter",
    title: "Threading with a Lock",
    category: "Misc",
    summary: "Race-condition-free shared counter.",
    stack: ["threading"],
    code: [
      "import threading",
      "",
      "counter = 0",
      "lock = threading.Lock()                          # mutual exclusion",
      "",
      "def worker():",
      "    global counter",
      "    for _ in range(10_000):",
      "        with lock:                               # critical section",
      "            counter += 1                          # would race without the lock",
      "",
      "threads = [threading.Thread(target=worker) for _ in range(4)]",
      "for t in threads: t.start()",
      "for t in threads: t.join()                       # wait for all to finish",
      "print(counter)                                    # 40000",
    ].join("\n"),
  }),
  P({
    slug: "async-sleep",
    title: "Async / Await Basics",
    category: "Misc",
    summary: "Concurrent tasks with asyncio.",
    stack: ["asyncio"],
    code: [
      "import asyncio, time",
      "",
      "async def work(name, secs):                     # 'async def' creates a coroutine",
      "    print(name, \"start\")",
      "    await asyncio.sleep(secs)                   # non-blocking sleep",
      "    print(name, \"done\")",
      "",
      "async def main():",
      "    t0 = time.perf_counter()",
      "    await asyncio.gather(work(\"a\", 0.2), work(\"b\", 0.2), work(\"c\", 0.2))",
      "    print(f\"elapsed {time.perf_counter()-t0:.2f}s\")  # ~0.2s, not 0.6s",
      "",
      "asyncio.run(main())",
    ].join("\n"),
  }),
  P({
    slug: "tic-tac-toe-ai",
    title: "Tic-Tac-Toe AI (Minimax)",
    category: "Games",
    summary: "Unbeatable AI in ~20 lines.",
    stack: ["recursion"],
    code: [
      "WINS=[(0,1,2),(3,4,5),(6,7,8),(0,3,6),(1,4,7),(2,5,8),(0,4,8),(2,4,6)]",
      "def winner(b):",
      "    for a,c,d in WINS:",
      "        if b[a]==b[c]==b[d]!=' ': return b[a]",
      "    return None",
      "def minimax(b, player):                          # returns (score, move)",
      "    w = winner(b)",
      "    if w == 'X': return 1, None                  # X is maximiser",
      "    if w == 'O': return -1, None                 # O is minimiser",
      "    if ' ' not in b: return 0, None              # draw",
      "    best = (-2 if player == 'X' else 2, None)",
      "    for i, c in enumerate(b):",
      "        if c != ' ': continue",
      "        nb = b[:i] + player + b[i+1:]            # try move i",
      "        score,_ = minimax(nb, 'O' if player == 'X' else 'X')",
      "        if (player == 'X' and score > best[0]) or (player == 'O' and score < best[0]):",
      "            best = (score, i)",
      "    return best",
      "",
      "print(minimax(\"X O   X  \", \"O\"))            # AI's best response",
    ].join("\n"),
  }),
  P({
    slug: "n-queens",
    title: "N-Queens (Backtracking)",
    category: "Algorithms",
    summary: "Place N queens with no conflicts.",
    stack: ["recursion"],
    code: [
      "def solve(n):",
      "    solutions = []",
      "    def backtrack(row, cols, diag1, diag2, placement):",
      "        if row == n:                              # placed all queens",
      "            solutions.append(placement[:]); return",
      "        for c in range(n):",
      "            if c in cols or (row - c) in diag1 or (row + c) in diag2:",
      "                continue                          # conflict -> skip",
      "            placement.append(c)",
      "            backtrack(row+1, cols|{c}, diag1|{row-c}, diag2|{row+c}, placement)",
      "            placement.pop()                       # undo (backtrack)",
      "    backtrack(0, set(), set(), set(), [])",
      "    return solutions",
      "",
      "sols = solve(4)",
      "print(len(sols), \"solutions for N=4\")",
      "for s in sols: print(s)",
    ].join("\n"),
  }),

  // ============================================================
  // EXTRAS to comfortably exceed 100
  // ============================================================
  P({
    slug: "temp-converter",
    title: "Temperature Converter",
    category: "Math",
    summary: "Celsius <-> Fahrenheit.",
    stack: ["functions"],
    code: [
      "def c_to_f(c): return c * 9 / 5 + 32          # formula derived from boiling/freezing",
      "def f_to_c(f): return (f - 32) * 5 / 9",
      "print(c_to_f(100), f_to_c(212))               # 212.0 100.0",
    ].join("\n"),
  }),
  P({
    slug: "bmi-calculator",
    title: "BMI Calculator",
    category: "Math",
    summary: "Classify body mass index.",
    stack: ["functions"],
    code: [
      "def bmi(kg, m):",
      "    return kg / (m * m)                        # kg / metres^2",
      "def classify(b):",
      "    if b < 18.5: return \"under\"",
      "    if b < 25:   return \"healthy\"",
      "    if b < 30:   return \"over\"",
      "    return \"obese\"",
      "v = bmi(72, 1.78)",
      "print(round(v, 1), classify(v))",
    ].join("\n"),
  }),
  P({
    slug: "tip-calculator",
    title: "Tip Calculator",
    category: "Math",
    summary: "Split a bill across people.",
    stack: ["functions"],
    code: [
      "bill, tip_pct, people = 87.50, 0.18, 3        # constants for the demo",
      "total = bill * (1 + tip_pct)                   # add the tip",
      "per_person = total / people",
      "print(f\"total ${total:.2f}, each ${per_person:.2f}\")  # format to 2 decimal places",
    ].join("\n"),
  }),
  P({
    slug: "url-shortener",
    title: "URL Shortener (in-memory)",
    category: "Misc",
    summary: "Map random codes to long URLs.",
    stack: ["secrets"],
    code: [
      "import secrets, string",
      "ALPHA = string.ascii_letters + string.digits        # base62",
      "db = {}                                                # code -> url",
      "",
      "def shorten(url):",
      "    code = \"\".join(secrets.choice(ALPHA) for _ in range(6))  # 6-char id",
      "    db[code] = url",
      "    return code",
      "",
      "def expand(code): return db.get(code)",
      "",
      "c = shorten(\"https://example.com/very/long/path\")",
      "print(c, \"->\", expand(c))",
    ].join("\n"),
  }),
  P({
    slug: "json-pretty-print",
    title: "JSON Pretty-Printer",
    category: "Files & Utilities",
    summary: "Re-format compact JSON for humans.",
    stack: ["json"],
    code: [
      "import json",
      "raw = '{\"name\":\"Ada\",\"skills\":[\"py\",\"hs\"],\"active\":true}'",
      "obj = json.loads(raw)                          # parse to a Python object",
      "print(json.dumps(obj, indent=2, sort_keys=True))",
    ].join("\n"),
  }),
];

export const projectCategories = Array.from(
  new Set(projects.map((p) => p.category))
);
