/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferenceIndexRouteImport } from './routes/reference.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as CurriculumIndexRouteImport } from './routes/curriculum.index'
import { Route as ProblemsSlugRouteImport } from './routes/problems.$slug'
import { Route as CurriculumModuleIndexRouteImport } from './routes/curriculum.$module.index'
import { Route as CurriculumModuleLessonRouteImport } from './routes/curriculum.$module.$lesson'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceIndexRoute = ReferenceIndexRouteImport.update({
  id: '/reference/',
  path: '/reference/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumIndexRoute = CurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsSlugRoute = ProblemsSlugRouteImport.update({
  id: '/problems/$slug',
  path: '/problems/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumModuleIndexRoute = CurriculumModuleIndexRouteImport.update({
  id: '/curriculum/$module/',
  path: '/curriculum/$module/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumModuleLessonRoute = CurriculumModuleLessonRouteImport.update({
  id: '/curriculum/$module/$lesson',
  path: '/curriculum/$module/$lesson',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/reference/': typeof ReferenceIndexRoute
  '/curriculum/$module/$lesson': typeof CurriculumModuleLessonRoute
  '/curriculum/$module/': typeof CurriculumModuleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/curriculum': typeof CurriculumIndexRoute
  '/problems': typeof ProblemsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/reference': typeof ReferenceIndexRoute
  '/curriculum/$module/$lesson': typeof CurriculumModuleLessonRoute
  '/curriculum/$module': typeof CurriculumModuleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/reference/': typeof ReferenceIndexRoute
  '/curriculum/$module/$lesson': typeof CurriculumModuleLessonRoute
  '/curriculum/$module/': typeof CurriculumModuleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/problems/$slug'
    | '/curriculum/'
    | '/problems/'
    | '/projects/'
    | '/reference/'
    | '/curriculum/$module/$lesson'
    | '/curriculum/$module/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/problems/$slug'
    | '/curriculum'
    | '/problems'
    | '/projects'
    | '/reference'
    | '/curriculum/$module/$lesson'
    | '/curriculum/$module'
  id:
    | '__root__'
    | '/'
    | '/problems/$slug'
    | '/curriculum/'
    | '/problems/'
    | '/projects/'
    | '/reference/'
    | '/curriculum/$module/$lesson'
    | '/curriculum/$module/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProblemsSlugRoute: typeof ProblemsSlugRoute
  CurriculumIndexRoute: typeof CurriculumIndexRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ReferenceIndexRoute: typeof ReferenceIndexRoute
  CurriculumModuleLessonRoute: typeof CurriculumModuleLessonRoute
  CurriculumModuleIndexRoute: typeof CurriculumModuleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/': {
      id: '/reference/'
      path: '/reference'
      fullPath: '/reference/'
      preLoaderRoute: typeof ReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/': {
      id: '/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof CurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$slug': {
      id: '/problems/$slug'
      path: '/problems/$slug'
      fullPath: '/problems/$slug'
      preLoaderRoute: typeof ProblemsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$module/': {
      id: '/curriculum/$module/'
      path: '/curriculum/$module'
      fullPath: '/curriculum/$module/'
      preLoaderRoute: typeof CurriculumModuleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$module/$lesson': {
      id: '/curriculum/$module/$lesson'
      path: '/curriculum/$module/$lesson'
      fullPath: '/curriculum/$module/$lesson'
      preLoaderRoute: typeof CurriculumModuleLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProblemsSlugRoute: ProblemsSlugRoute,
  CurriculumIndexRoute: CurriculumIndexRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ReferenceIndexRoute: ReferenceIndexRoute,
  CurriculumModuleLessonRoute: CurriculumModuleLessonRoute,
  CurriculumModuleIndexRoute: CurriculumModuleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
